version: '3.8'

services:
  database:
    image: mysql:${MYSQL_VERSION:-latest}
    container_name: ${CONTAINER_PREFIX}_database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./data:/var/lib/mysql:rw
      # Uncomment if you want to run your own init-db
      #- ./db-dump:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:3306"
  #    Uncomment if you want to setup your database charset
  #    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  php-apache:
    container_name: ${CONTAINER_PREFIX}_php-apache
    build:
      context: ./php
    ports:
      - '${APACHE_PORT}:80'
    volumes:
      - ${PROJECT_ROOT}:/var/www/laravel_docker
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database